export const STORAGE_KEY = 'lvp_portal_session_v2';
export const API = {
  sendOtp:             '/api/auth?action=send-otp',
  verifyOtp:           '/api/auth?action=verify-otp',
  portalSession:       '/api/portal?action=session',
  portalData:          '/api/portal?action=data',
  logAccess:           '/api/portal?action=log',
  adminDashboard:      '/api/admin?action=dashboard',
  getLogs:             '/api/admin?action=logs',
  upsertClient:        '/api/clients?action=upsert',
  updateClientProfile: '/api/clients?action=update-profile',
  upsertWhitelist:     '/api/clients?action=upsert-whitelist',
  upsertProject:       '/api/projects?action=upsert',
  updateProjectBasics: '/api/projects?action=update-basics',
  archiveProject:      '/api/projects?action=archive',
  deleteProject:       '/api/projects?action=delete',
  addQuoteVersion:     '/api/quotes?action=add-version',
  setCurrentQuote:     '/api/quotes?action=set-current',
  approveQuote:        '/api/quotes?action=approve',
  signQuote:           '/api/quotes?action=sign',
  addProjectAsset:     '/api/assets',
  signContract:        '/api/contracts',
};
